add endpoint add multiple subscriber to mailing list
kitabisa/moosend-go-client pull request #4
Opened 2021-07-26 07:32 UTC by AhmadDzakiN

Add Moosend Endpoint Add Multiple Subscriber to Mailing List

2021-07-26 09:57 UTC, azisuazusa requested changes

2021-07-26 09:57 UTC, azisuazusa commented on subscriber/structs.go
> +	Context  []Subscriber 	`json:"Context,omitempty"`
Mas @AhmadDzakiN kayanya ini gabisa deh, kalo liat dari Apiarynya beda beda responseya, ada yang memang `Context`nya array dan ada juga yang single.

2021-07-26 10:18 UTC, AhmadDzakiN commented on subscriber/structs.go
> +	Context  []Subscriber 	`json:"Context,omitempty"`
updated mas @azisuazusa

2021-07-26 10:19 UTC, azisuazusa approved these changes

2021-07-27 04:58 UTC, abhisuta approved these changes

2021-07-27 13:09 UTC, merged